name: ${DOCKER_NAME:-huly}

services:
  cockroach:
    image: cockroachdb/cockroach:latest-v24.2
    command: start-single-node --accept-sql-without-tls
    environment:
      - COCKROACH_DATABASE=${CR_DATABASE:-defaultdb}
      - COCKROACH_USER=${CR_USERNAME:-selfhost}
      - COCKROACH_PASSWORD=${CR_USER_PASSWORD:-cr_secret}
    volumes:
      - ${VOLUME_CR_DATA_PATH:-cr_data}:/cockroach/cockroach-data
      - ${VOLUME_CR_CERTS_PATH:-cr_certs}:/cockroach/certs
    restart: unless-stopped
    networks: [huly_net]

  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v24.3.6
    command:
      - redpanda
      - start
      - --kafka-addr
      - internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr
      - internal://redpanda:9092,external://localhost:19092
      - --pandaproxy-addr
      - internal://0.0.0.0:8082,external://0.0.0.0:18082
      - --advertise-pandaproxy-addr
      - internal://redpanda:8082,external://localhost:18082
      - --schema-registry-addr
      - internal://0.0.0.0:8081,external://0.0.0.0:18081
      - --rpc-addr
      - redpanda:33145
      - --advertise-rpc-addr
      - redpanda:33145
      - --mode
      - dev-container
      - --smp
      - "1"
      - --default-log-level=info
    container_name: redpanda
    volumes:
      - ${VOLUME_REDPANDA_PATH:-redpanda}:/var/lib/redpanda/data
    environment:
      - REDPANDA_SUPERUSER_USERNAME=${REDPANDA_ADMIN_USER:-superadmin}
      - REDPANDA_SUPERUSER_PASSWORD=${REDPANDA_ADMIN_PWD:-panda_secret}
    networks: [huly_net]
    restart: unless-stopped

  minio:
    image: minio/minio
    command: server /data --address ":9000" --console-address ":9001"
    volumes:
      - ${VOLUME_FILES_PATH:-files}:/data
    restart: unless-stopped
    networks: [huly_net]

  elastic:
    image: elasticsearch:7.14.2
    command: >
      /bin/sh -c "./bin/elasticsearch-plugin list | grep -q ingest-attachment ||
      yes | ./bin/elasticsearch-plugin install --silent ingest-attachment;
      /usr/local/bin/docker-entrypoint.sh eswrapper"
    volumes:
      - ${VOLUME_ELASTIC_PATH:-elastic}:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1024m -Xmx1024m
    restart: unless-stopped
    networks: [huly_net]

  rekoni:
    image: hardcoreeng/rekoni-service:${HULY_VERSION}
    environment:
      - SECRET=${SECRET}
    deploy:
      resources:
        limits:
          memory: 500M
    restart: unless-stopped
    networks: [huly_net]

  transactor:
    image: hardcoreeng/transactor:${HULY_VERSION}
    environment:
      - SERVER_PORT=3333
      - SERVER_SECRET=${SECRET}
      - DB_URL=${CR_DB_URL}
      - STORAGE_CONFIG=minio|minio?accessKey=minioadmin&secretKey=minioadmin
      - FRONT_URL=http://${HOST_ADDRESS}
      - ACCOUNTS_URL=http://account:3000
      - FULLTEXT_URL=http://fulltext:4700
      - STATS_URL=http://stats:4900
      - LAST_NAME_FIRST=${LAST_NAME_FIRST:-true}
      - QUEUE_CONFIG=redpanda:9092
    restart: unless-stopped
    networks: [huly_net]

  collaborator:
    image: hardcoreeng/collaborator:${HULY_VERSION}
    environment:
      - COLLABORATOR_PORT=3078
      - SECRET=${SECRET}
      - ACCOUNTS_URL=http://account:3000
      - STATS_URL=http://stats:4900
      - STORAGE_CONFIG=minio|minio?accessKey=minioadmin&secretKey=minioadmin
    restart: unless-stopped
    networks: [huly_net]

  account:
    image: hardcoreeng/account:${HULY_VERSION}
    environment:
      - SERVER_PORT=3000
      - SERVER_SECRET=${SECRET}
      - DB_URL=${CR_DB_URL}
      - TRANSACTOR_URL=ws://transactor:3333;ws://${HOST_ADDRESS}/_transactor
      - STORAGE_CONFIG=minio|minio?accessKey=minioadmin&secretKey=minioadmin
      - FRONT_URL=http://${HOST_ADDRESS}
      - STATS_URL=http://${HOST_ADDRESS}/_stats
      - MODEL_ENABLED=*
      - ACCOUNTS_URL=http://${HOST_ADDRESS}/_accounts
      - ACCOUNT_PORT=3000
      - QUEUE_CONFIG=redpanda:9092
    restart: unless-stopped
    networks: [huly_net]

  workspace:
    image: hardcoreeng/workspace:${HULY_VERSION}
    environment:
      - SERVER_SECRET=${SECRET}
      - DB_URL=${CR_DB_URL}
      - TRANSACTOR_URL=ws://transactor:3333;ws://${HOST_ADDRESS}/_transactor
      - STORAGE_CONFIG=minio|minio?accessKey=minioadmin&secretKey=minioadmin
      - MODEL_ENABLED=*
      - ACCOUNTS_URL=http://account:3000
      - STATS_URL=http://stats:4900
      - QUEUE_CONFIG=redpanda:9092
      - ACCOUNTS_DB_URL=${CR_DB_URL}
    restart: unless-stopped
    networks: [huly_net]

  front:
    image: hardcoreeng/front:${HULY_VERSION}
    environment:
      - SERVER_PORT=8080
      - SERVER_SECRET=${SECRET}
      - ACCOUNTS_URL=http://${HOST_ADDRESS}/_accounts
      - ACCOUNTS_URL_INTERNAL=http://account:3000
      - REKONI_URL=http://${HOST_ADDRESS}/_rekoni
      - STATS_URL=http://${HOST_ADDRESS}/_stats
      - UPLOAD_URL=/files
      - ELASTIC_URL=http://elastic:9200
      - COLLABORATOR_URL=ws://${HOST_ADDRESS}/_collaborator
      - STORAGE_CONFIG=minio|minio?accessKey=minioadmin&secretKey=minioadmin
      - TITLE=${TITLE:-Huly Self Host}
      - DEFAULT_LANGUAGE=${DEFAULT_LANGUAGE:-en}
      - LAST_NAME_FIRST=${LAST_NAME_FIRST:-true}
      - DESKTOP_UPDATES_CHANNEL=${DESKTOP_CHANNEL:-selfhost}
    restart: unless-stopped
    networks:
      - huly_net
      - proxy
    labels:
      - traefik.enable=true

      # Base UI
      - traefik.http.routers.huly-ui.entrypoints=web
      - traefik.http.routers.huly-ui.rule=PathPrefix(`/`)
      - traefik.http.routers.huly-ui.service=huly-ui
      - traefik.http.services.huly-ui.loadbalancer.server.port=8080
      # give API routes higher priority than /
      - traefik.http.routers.huly-ui.priority=1

  fulltext:
    image: hardcoreeng/fulltext:${HULY_VERSION}
    environment:
      - SERVER_SECRET=${SECRET}
      - DB_URL=${CR_DB_URL}
      - FULLTEXT_DB_URL=http://elastic:9200
      - ELASTIC_INDEX_NAME=huly_storage_index
      - STORAGE_CONFIG=minio|minio?accessKey=minioadmin&secretKey=minioadmin
      - REKONI_URL=http://rekoni:4004
      - ACCOUNTS_URL=http://account:3000
      - STATS_URL=http://stats:4900
      - QUEUE_CONFIG=redpanda:9092
    restart: unless-stopped
    networks: [huly_net]

  stats:
    image: hardcoreeng/stats:${HULY_VERSION}
    environment:
      - PORT=4900
      - SERVER_SECRET=${SECRET}
    restart: unless-stopped
    networks:
      - huly_net
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.huly-stats.entrypoints=web
      - traefik.http.routers.huly-stats.rule=PathPrefix(`/_stats`)
      - traefik.http.routers.huly-stats.priority=100
      - traefik.http.services.huly-stats.loadbalancer.server.port=4900

  rekoni-traefik:
    image: alpine:3.20
    command: sh -lc "sleep infinity"
    networks:
      - proxy
      - huly_net
    labels:
      - traefik.enable=true
      - traefik.http.routers.huly-rekoni.entrypoints=web
      - traefik.http.routers.huly-rekoni.rule=PathPrefix(`/_rekoni`)
      - traefik.http.routers.huly-rekoni.priority=100
      - traefik.http.services.huly-rekoni.loadbalancer.server.port=4004
    depends_on:
      - rekoni
    restart: unless-stopped

  account-traefik:
    image: alpine:3.20
    command: sh -lc "sleep infinity"
    networks:
      - proxy
      - huly_net
    labels:
      - traefik.enable=true
      - traefik.http.routers.huly-accounts.entrypoints=web
      - traefik.http.routers.huly-accounts.rule=PathPrefix(`/_accounts`)
      - traefik.http.routers.huly-accounts.priority=100
      - traefik.http.services.huly-accounts.loadbalancer.server.port=3000
    depends_on:
      - account
    restart: unless-stopped

  transactor-traefik:
    image: alpine:3.20
    command: sh -lc "sleep infinity"
    networks:
      - proxy
      - huly_net
    labels:
      - traefik.enable=true
      - traefik.http.routers.huly-transactor.entrypoints=web
      - traefik.http.routers.huly-transactor.rule=PathPrefix(`/_transactor`)
      - traefik.http.routers.huly-transactor.priority=100
      - traefik.http.services.huly-transactor.loadbalancer.server.port=3333
    depends_on:
      - transactor
    restart: unless-stopped

  collaborator-traefik:
    image: alpine:3.20
    command: sh -lc "sleep infinity"
    networks:
      - proxy
      - huly_net
    labels:
      - traefik.enable=true
      - traefik.http.routers.huly-collab.entrypoints=web
      - traefik.http.routers.huly-collab.rule=PathPrefix(`/_collaborator`)
      - traefik.http.routers.huly-collab.priority=100
      - traefik.http.services.huly-collab.loadbalancer.server.port=3078
    depends_on:
      - collaborator
    restart: unless-stopped

  minio-traefik:
    image: alpine:3.20
    command: sh -lc "sleep infinity"
    networks:
      - proxy
      - huly_net
    labels:
      - traefik.enable=true
      - traefik.http.routers.huly-files.entrypoints=web
      - traefik.http.routers.huly-files.rule=PathPrefix(`/files`)
      - traefik.http.routers.huly-files.priority=100
      - traefik.http.services.huly-files.loadbalancer.server.port=9000
    depends_on:
      - minio
    restart: unless-stopped

  kvs:
    image: hardcoreeng/hulykvs:${HULY_VERSION}
    depends_on:
      cockroach:
        condition: service_started
    environment:
      - HULY_DB_CONNECTION=${CR_DB_URL}
      - HULY_TOKEN_SECRET=${SECRET}
    restart: unless-stopped
    networks: [huly_net]

volumes:
  elastic:
  files:
  cr_data:
  cr_certs:
  redpanda:

networks:
  huly_net:
    name: huly_net
  proxy:
    external: true
